FROM centos:latest

RUN yum -y update &&\
    yum -y install \
    git \
    make \
    gcc-c++ \
    wget \
    bc \
    python3-devel \
    zlib-devel \
    fftw3-devel \
    mpich-devel && \
    yum clean all 

WORKDIR /srv/
ENV PATH /usr/lib64/mpich/bin:${PATH}
ENV LAMMPSDIR /srv/lammps/

RUN pip3 install numpy sklearn pandas natsort tqdm configparser

ENV LD_LIBRARY_PATH ${LD_LIBRARY_PATH}:$LAMMPSDIR/src
ENV PYTHONPATH ${PYTHONPATH}:$LAMMPSDIR/python

RUN git clone https://github.com/lammps/lammps

RUN cd lammps/src && make yes-snap && make mpi -j 4 mode=shlib LMP_INC="-DLAMMPS_GZIP -DLAMMPS_MEMALIGN=64 -DLAMMPS_EXCEPTIONS"

RUN yum -y install nano which

RUN ln -s /usr/bin/python3 /usr/bin/python && cd lammps/src && make install-python && python -c "import lammps;lmp = lammps.lammps()"

ENV FITSNAPDIR /srv/FitSNAP/
RUN git clone https://github.com/rmmilewi/FitSNAP
RUN cd FitSNAP/ && python -m fitsnap3 -h




